Name_first = str(input())
Name_last = str(input())
Address = str(input())
Gender = str(input())
Tel = str(input())

print("--- Customer Detail ---")
print(f"Name : {Name_first} {Name_last}")
print(f"Address : {Address}")
print(f"Gender : {Gender}")
print(f"Tel : {Tel}")
